# Generated by Django 5.1.1 on 2024-10-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0003_remove_cat_birth_date_cat_years"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cat",
            name="years",
        ),
        migrations.AddField(
            model_name="cat",
            name="birth_year",
            field=models.IntegerField(default=1, verbose_name="Год"),
            preserve_default=False,
        ),
    ]
