# Generated by Django 5.1.1 on 2024-10-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Кличка")),
                ("color", models.CharField(max_length=16, verbose_name="Окрас")),
                (
                    "hairiness",
                    models.CharField(max_length=16, verbose_name="Волосатость"),
                ),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
